# Generated by Django 3.2.24 on 2024-03-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('item_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('picture', 'Picture')], max_length=10)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
