# Generated by Django 5.0.1 on 2024-01-13 13:52

import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='chat_audio/', validators=[reports.models.validate_audio_extension]),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='chat_documents/', validators=[reports.models.validate_document_extension]),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/', validators=[reports.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='chat_videos/', validators=[reports.models.validate_video_extension]),
        ),
    ]
