# Generated by Django 5.0.1 on 2024-01-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_chatmessage_audio_alter_chatmessage_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat_audio/')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='chat_images/')),
            ],
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat_videos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='document',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='video',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='audios',
            field=models.ManyToManyField(blank=True, to='reports.audiofile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='documents',
            field=models.ManyToManyField(blank=True, to='reports.documentfile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='images',
            field=models.ManyToManyField(blank=True, to='reports.imagefile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='videos',
            field=models.ManyToManyField(blank=True, to='reports.videofile'),
        ),
    ]
