# Generated by Django 5.0.1 on 2024-01-13 14:39

import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_audiofile_documentfile_imagefile_videofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='audios',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='images',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='videos',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='chat_audio/', validators=[reports.models.validate_audio_extension], verbose_name='AudioFile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='chat_documents/', validators=[reports.models.validate_document_extension], verbose_name='DocumentFile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='chat_images/', validators=[reports.models.validate_image_extension], verbose_name='ImageFile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='chat_videos/', validators=[reports.models.validate_video_extension], verbose_name='VideoFile'),
        ),
        migrations.DeleteModel(
            name='AudioFile',
        ),
        migrations.DeleteModel(
            name='DocumentFile',
        ),
        migrations.DeleteModel(
            name='ImageFile',
        ),
        migrations.DeleteModel(
            name='VideoFile',
        ),
    ]
