# Generated by Django 5.0.1 on 2024-01-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
